// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

package com.test.rmi.chat.server;

public final class ChatServer_Stub
    extends java.rmi.server.RemoteStub
    implements com.test.rmi.chat.Chat, java.rmi.Remote
{
    private static final long serialVersionUID = 2;
    
    private static java.lang.reflect.Method $method_setClient_0;
    private static java.lang.reflect.Method $method_setMessage_1;
    
    static {
	try {
	    $method_setClient_0 = com.test.rmi.chat.Chat.class.getMethod("setClient", new java.lang.Class[] {com.test.rmi.chat.ChatMessage.class});
	    $method_setMessage_1 = com.test.rmi.chat.Chat.class.getMethod("setMessage", new java.lang.Class[] {java.lang.String.class});
	} catch (java.lang.NoSuchMethodException e) {
	    throw new java.lang.NoSuchMethodError(
		"stub class initialization failed");
	}
    }
    
    // constructors
    public ChatServer_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
    // methods from remote interfaces
    
    // implementation of setClient(ChatMessage)
    public void setClient(com.test.rmi.chat.ChatMessage $param_ChatMessage_1)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_setClient_0, new java.lang.Object[] {$param_ChatMessage_1}, 3116472429501082103L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of setMessage(String)
    public void setMessage(java.lang.String $param_String_1)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_setMessage_1, new java.lang.Object[] {$param_String_1}, -6512708111504182638L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
}
